/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef __PLAYER_CORE_JNI_INTERFACE__
#define __PLAYER_CORE_JNI_INTERFACE__
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 ** create instance and surface ...
	 */
	JNIEXPORT int JNICALL Java_nativeInterface_playerView_nativeOnCreate(JNIEnv* jenv, jobject obj,jobject connectivity_manager);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativeOnResume(JNIEnv* jenv, jobject obj);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativeOnPause(JNIEnv* jenv, jobject obj,jint wait);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativeOnDelete(JNIEnv* jenv, jobject obj);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativeSetSurface(JNIEnv* jenv, jobject obj, jobject surface);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativeSurfaceChanged(JNIEnv* jenv, jobject obj,jobject surface);

	/*
	 ** player start, pause, stop ...
	 */ 
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativePlayerStart(JNIEnv* jenv, jobject obj,jstring url, jint start,jint buftime,jint video_scale);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativePlayerLoad(JNIEnv* jenv, jobject obj,jstring url, jint start,jint buftime,jint video_scale);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativePlayerPause(JNIEnv* jenv, jobject obj,jint);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativePlayerStop(JNIEnv* jenv, jobject obj);
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativePlayerResume(JNIEnv* jenv, jobject obj);
	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativePlayerGetBufTime(JNIEnv* jenv, jobject obj);
	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativePlayerGetPlayPos(JNIEnv* jenv, jobject obj);
	
	/* 1 mute, 0 not mute */
	JNIEXPORT void JNICALL Java_nativeInterface_playerView_nativePlayerMute(JNIEnv* jenv, jobject obj, jint);

	/*
	 * * get media information...
	 */
	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativeGetVideoWidth(JNIEnv* jenv, jobject obj);
	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativeGetVideoHeight(JNIEnv* jenv, jobject obj);

	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativePlayerGetLength(JNIEnv* jenv, jobject obj);
	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativePlayerSeek(JNIEnv* jenv, jobject obj,jint ms);

	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativePlayerVideoScale(JNIEnv* jenv, jobject obj,jint scale);
	JNIEXPORT jint JNICALL Java_nativeInterface_playerView_nativePlayerVideoMirror(JNIEnv* jenv, jobject obj,jint mirror);
	
#ifdef __cplusplus
}
#endif
#endif //__PLAYER_CORE_JNI_INTERFACE__
